/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene1.ls
 */
export class Scene2RTBase extends Laya.Scene {
    public TextArea: Laya.TextArea;
    public Button_toggle: Laya.Button;
}

