/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene4.ls
 */
export class Scene5RTBase extends Laya.Scene {
    public Image_bg: Laya.Image;
    public Box_words: Laya.Box;
    public Label_blink: Laya.Label;
    public Button_test: Laya.Button;
}

