/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene7.ls
 */
export class Scene8RTBase extends Laya.Scene {
    public Sprite: Laya.Sprite;
    public Sprite_Mask: Laya.Sprite;
}

