/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene5.ls
 */
export class Scene6RTBase extends Laya.Scene {
    public List_menu: Laya.List;
}

