/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene3.ls
 */
export class Scene4RTBase extends Laya.Scene {
    public List_bag: Laya.List;
    public Sprite_head: Laya.Sprite;
    public groove_head: Laya.Image;
    public Sprite_body: Laya.Sprite;
    public groove_body: Laya.Image;
    public Sprite_hand: Laya.Sprite;
    public groove_hand: Laya.Image;
    public Sprite_foot: Laya.Sprite;
    public groove_foot: Laya.Image;
}

