/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene6.ls
 */
export class Scene7RTBase extends Laya.Scene {
    public Panel_Content: Laya.Panel;
    public TextInput_Message: Laya.TextInput;
    public Button_Send: Laya.Button;
}

