/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene8.ls
 */
export class Scene9RTBase extends Laya.Scene {
    public List_Craft: Laya.List;
    public List_Bag: Laya.List;
    public Button_Clear: Laya.Button;
}

