/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene2.ls
 */
export class Scene3RTBase extends Laya.Scene {
    public Box: Laya.Box;
    public HBox_btnList: Laya.HBox;
    public Button_left: Laya.Button;
    public Button_right: Laya.Button;
}

